name: "MVN_TEST"

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 7 * * *"

jobs:
  java_update:
    name: "java"
    uses: codespacedev/spring-boot-native-example/.github/workflows/wc_java_update.yml@main
    secrets:
      GITHUB_TOKEN: ${{secrets.CI_TOKEN_WORKFLOW}}
  java_test:
    needs: "java_update"
    name: "java"
    uses: codespacedev/spring-boot-native-example/.github/workflows/wc_java_test.yml@main
    secrets:
      GITHUB_TOKEN: ${{secrets.CI_TOKEN_WORKFLOW}}
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
