name: "JAVA_TEST"

on:
  workflow_dispatch:
  push:
    # Already covered by "auto_release.yml" workflow
    branches:
      - '!master'
      - '!main'
      - '!default'

jobs:
  java_test:
    name: "java"
    uses: codespacedev/commons/.github/workflows/wc_java_test.yml@main
    secrets:
      G_TOKEN: ${{secrets.CI_TOKEN_WORKFLOW}}
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
